name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ukui-kwin source
      uses: actions/checkout@v2

    - name: Update apt repository
      run: sudo apt-get update -y

    - name: Install latest Qt5
      run: sudo apt-get -y install build-essential qt5-default qttools5-dev-tools

    - name: Instal dependcies
      run: sudo apt-get install -y breeze-dev cmake debhelper extra-cmake-modules kinit-dev kscreenlocker-dev libcap-dev libdrm-dev libegl1-mesa-dev libepoxy-dev libfontconfig1-dev libfreetype6-dev libgbm-dev libice-dev libinput-dev libkdecorations2-dev libkf5activities-dev libkf5completion-dev libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev libkf5crash-dev libkf5declarative-dev libkf5doctools-dev libkf5globalaccel-dev libkf5i18n-dev libkf5iconthemes-dev libkf5idletime-dev libkf5kcmutils-dev libkf5kio-dev libkf5newstuff-dev libkf5notifications-dev libkf5package-dev libkf5plasma-dev libkf5service-dev libkf5textwidgets-dev libkf5wayland-dev libkf5widgetsaddons-dev libkf5windowsystem-dev libkf5xmlgui-dev  libqt5sensors5-dev libqt5x11extras5-dev  libsm-dev libudev-dev libwayland-dev  libx11-xcb-dev libxcb-composite0-dev libxcb-cursor-dev libxcb-damage0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xtest0-dev libxcb1-dev libxcursor-dev libxi-dev libxkbcommon-dev pkg-config pkg-kde-tools qtbase5-dev qtbase5-private-dev qtdeclarative5-dev qtscript5-dev qttools5-dev libgsettings-qt-dev

    - name: CMake generate & Make
      run: mkdir -p build && cd build && cmake .. && make -j$(nproc)
